routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web', 'auth']], function() {
    Route::get('/home', function() {
        if(Auth::user()->admin == 0) {
            return view('member.member-home');
        } else {
            $users['users'] = \App\User::all();
            return view('admin.admin-home', $users);
        }
    });
});

Route::group(['middleware' => ['web', 'auth']], function() {
    Route::resource('book', 'BookController');
    Route::resource('user', 'UserController');
    Route::resource('transaction', 'TransactionController');
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'title', 'author', 'price',
    ];

    public function transaction(){
        return $this->belongsToMany('App\Transaction');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class BookController extends Controller
{
    public function index()
    {
        $books = DB::table('books')->get();
        return view('book.index', ['books' => $books]);
    }
    public function create()
    {
        return view('book.create');
    }
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'author'=>'required',
            'price'=>'required'
        ]);

        $book = new Book();
        $book->title = $request->title;
        $book->author = $request->author;
        $book->price = $request->price;
        $book->count = 0;
        
        $book->save();
        // return response()->json($book, 201);
        return response()->json(['success' => 'Add new book sucessfully!']);
        // return redirect('/book');
    }
    public function edit($id)
    {
        $book = Book::find($id);
        return view('book.update', compact('book'));
    }
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'author' => 'required',
            'price' => 'required',
        ]);
        $book = Book::find($id);
        $book->title = $request->get('title');
        $book->author = $request->get('author');
        $book->price = $request->get('price');
        $book->save();
        // return redirect('/book')->with('success', 'Book updated!');
        return response()->json(['success' => 'Update book sucessfully!']);
    }
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        // return redirect('/book')->with('success', 'Book deleted!');
        return response()->json(['success' => 'Book delete sucessfully!']);
    }
}

resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Book
                    <a class="nav-link float-right" href="{{ url('/book') }}">{{ __('View All Book') }}</a>
                </div>
                
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form method="POST" action="{{ url('book') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Book Title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="author" class="col-md-4 col-form-label text-md-right">{{ __('Author') }}</label>

                            <div class="col-md-6">
                                <input id="author" type="text" class="form-control @error('author') is-invalid @enderror" name="author" value="{{ old('author') }}" required autocomplete="author" autofocus>

                                @error('author')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Daily Price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}" required autocomplete="price" autofocus>

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/book/index- admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">View All Book
                    <a class="nav-link float-right" href="{{ url('/book/create') }}">{{ __('Add Book') }}</a>
                </div>
                

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table border="2">
                        <tr>
                            <th>Book Title</th>
                            <th>Author</th>
                            <th>Daily Price</th>
                            <th>Book Count</th>
                            <th>Option</th>
                        </tr>
                        @foreach($books as $book)
                        <tr>
                            <td>{{ $book->title }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->price }}</td>
                            <td>{{ $book->count }}</td>
                            <td>
                                <a href="/book/edit/{{ $book->id }}">Edit</a>
                                |
                                <a href="/book/hapus/{{ $book->id }}">Delete</a>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">View All Book
                    @if(Auth::user()->admin == 1)
                    <a class="nav-link float-right" href="{{ url('/book/create') }}">{{ __('Add Book') }}</a>
                    @else
                    @endif
                </div>
                

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{-- {{ session('status') }} --}}
                            {{ session()->get('success') }}
                        </div>
                    @endif

                    <table border="2">
                        <tr>
                            <th>Book Title</th>
                            <th>Author</th>
                            <th>Daily Price</th>
                            <th>Book Count</th>
                            @if(Auth::user()->admin == 1)
                            <th>Option</th>
                            @endif
                        </tr>
                        @foreach($books as $book)
                        <tr>
                            <td>{{ $book->title }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->price }}</td>
                            <td>{{ $book->count }}</td>
                            @if(Auth::user()->admin == 1)
                            <td>
                                <a href="{{ route('book.edit', $book->id)}}" class="btn btn-primary">Edit</a>
                                |
                                <form action="{{ route('book.destroy', $book->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                            @else
                            @endif
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/book/update.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a book</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('book.update', $book->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" value={{ $book->title }} />
            </div>

            <div class="form-group">
                <label for="author">Author:</label>
                <input type="text" class="form-control" name="author" value={{ $book->author }} />
            </div>

            <div class="form-group">
                <label for="price">Price:</label>
                <input type="text" class="form-control" name="price" value={{ $book->price }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection